feat:add tests job

diff --git a/.github/workflows/golangci-lint.yml b/.github/workflows/golangci-lint.yml
--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -11,6 +11,30 @@ permissions:
   # pull-requests: read
 
 jobs:
+  test:
+    name: Run Tests
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
+      - name: Set up Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.21
+
+      - name: Run Tests
+        run: go test ./...
+
+      - name: Check Test Results
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Tests passed"
+          else
+            echo "Tests failed. Code cannot be merged to production."
+            exit 1
+          fi
   golangci:
     name: lint
     runs-on: ubuntu-latest
